server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/signin
    password: 1111
    username: sa
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
logging:
  level:
    root: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true