server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://123.57.29.247:3306/signin?serverTimezone=UTC
    password: 11111111
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
mybatis:
  configuration:
    map-underscore-to-camel-case: true